version: '3'

services:
  apache-php:
    build: ./php
    volumes:
      - ./:/var/www/html/
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "8080:80"

    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
